Coded ClassSchedule Model, will work on api
YixuanSeanZhou/GaryPlanner pull request #54
Opened 2020-11-07 23:16 UTC by j3li

#PR: 
Related Issues: Tag the issue here! Use the #38 
Author @j3li 
Reviewers: You can do multiple reviewers @YixuanSeanZhou 

Description: Implemented ClassSchedule Model

2020-11-07 23:57 UTC, YixuanSeanZhou requested changes
Great work! But please look at my comments and make some changes!

2020-11-07 23:57 UTC, YixuanSeanZhou commented on back_end/src/models/class_schedule.py
> +    end_time = db.Column(db.Time, nullable=False)
I guess we need to set the time to `String` type and parse it later

2020-11-07 23:57 UTC, YixuanSeanZhou commented on back_end/src/models/class_schedule.py
> +            class_id=class_id)
This is a style thing, and maybe if you install flask8, it should help!

2020-11-07 23:57 UTC, YixuanSeanZhou commented on back_end/src/models/class_schedule.py
> +    class_id = db.Column(db.Integer, unique=True, nullable=False)
I thought this would be a foreign key? To `Class.id`. So maybe `db.Column(db.Integer, unique=True, ForeignKey="Class.id", nullable=False)`

2020-11-07 23:57 UTC, YixuanSeanZhou commented on back_end/src/models/class_schedule.py
> +                    end_time: time, days: int, instructor: str) -> bool:
Should days of type String?

2020-11-07 23:57 UTC, YixuanSeanZhou commented on back_end/src/models/class_schedule.py
> +        class_schedules = list(map(lambda x: x.to_json(), class_schedules))
Like I commented on David's PR, we should not do `to_json()` in the model, but call it in APIs

2020-11-07 23:57 UTC, YixuanSeanZhou commented on back_end/src/models/class_schedule.py
> +    def get_class_schedules() -> List[ClassSchedule]:
In the future, this method should also have options to filter classes offered at specific dates (MWF) and times(10 pm - 2 pm)!

2020-11-12 21:52 UTC, YixuanSeanZhou requested changes
Everything looks great expect the small thing that I pointed out. Also please pull main and merge it to test out the foreign key with all class.

2020-11-12 21:52 UTC, YixuanSeanZhou commented on back_end/src/apis/class_schedule.py
> +            return jsonify({'reason': 'success', 'result': {}}), 200
Maybe this should not be success, reason should be no class found, with 300 as indicator.

2020-11-14 23:17 UTC, Korosense11 commented on back_end/src/apis/class_schedule.py
> +    if created:
return the object as well

2020-11-14 23:20 UTC, Korosense11 commented on back_end/src/apis/class_schedule.py
> +        return jsonify({'reason': 'failed', 'result': result}), 300
No need to return result if failed (I think)

2020-11-14 23:23 UTC, d5song commented on back_end/src/apis/class_schedule.py
>          return jsonify({'reason': 'failed', 'result': result}), 300
Do you need to return result as json even if update failed?

2020-11-14 23:24 UTC, Korosense11 commented on back_end/src/models/class_schedule.py
> +            return False    # class already exists in db
return False, None

2020-11-14 23:24 UTC, Korosense11 commented on back_end/src/models/class_schedule.py
> +        return True
return True, class_schedule (I think)

2020-12-06 04:29 UTC, closed without merging